### ISSUE TITLE
Linux 代理工具无法使用

### ISSUE THREAD

**Issue by YidaozhanYa** [Diving-Fish/maimaidx-prober#44]
系统：Arch Linux (内核版本 5.18.6，gcc 12.1.0)
微信使用 deepin-wine 运行，无论使用 `http_proxy` `https_proxy` 环境变量，还是 proxychains 工具，又或是微信的代理设置，均无法连接，打开公众号后是舞萌首页，并且代理程序出现 go 报错信息。

![图片](https://user-images.githubusercontent.com/73830635/176999151-47c3fd88-de52-4d60-8f2b-4c61d6ecdf83.png)

**Comment by WhitePr** [comment]
Termux上也有这个问题 不过无法打开网页 
这是log

2023/04/01 17:02:51 http: panic serving 127.0.0.1:41688: runtime error: index out of range [0] with length 0
goroutine 22 [running]:
net/http.(*conn).serve.func1()
        /data/data/com.termux/files/usr/lib/go/src/net/http/server.go:1854 +0xb0
panic({0x5936279340, 0x400001a318})
        /data/data/com.termux/files/usr/lib/go/src/runtime/panic.go:890 +0x248
github.com/elazarl/goproxy.signHost({{0x0, 0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        /data/data/com.termux/files/home/go/pkg/mod/github.com/elazarl/goproxy@v0.0.0-20210110162100-a92cc753f88e/signer.go:44 +0x8b8
github.com/elazarl/goproxy.TLSConfigFromCA.func1.1(...)
        /data/data/com.termux/files/home/go/pkg/mod/github.com/elazarl/goproxy@v0.0.0-20210110162100-a92cc753f88e/https.go:434
github.com/elazarl/goproxy.TLSConfigFromCA.func1({0x4000020687, 0x17}, 0x400007aba0)
        /data/data/com.termux/files/home/go/pkg/mod/github.com/elazarl/goproxy@v0.0.0-20210110162100-a92cc753f88e/https.go:439 +0x208
github.com/elazarl/goproxy.(*ProxyHttpServer).handleHttps(0x4000111180, {0x5936298d80?, 0x400014c2a0}, 0x40000c2300)
        /data/data/com.termux/files/home/go/pkg/mod/github.com/elazarl/goproxy@v0.0.0-20210110162100-a92cc753f88e/https.go:184 +0x3d8
github.com/elazarl/goproxy.(*ProxyHttpServer).ServeHTTP(0x0?, {0x5936298d80?, 0x400014c2a0?}, 0x59361c5038?)
        /data/data/com.termux/files/home/go/pkg/mod/github.com/elazarl/goproxy@v0.0.0-20210110162100-a92cc753f88e/proxy.go:114 +0xb0
net/http.serverHandler.ServeHTTP({0x400032d8f0?}, {0x5936298d80, 0x400014c2a0}, 0x40000c2300)
        /data/data/com.termux/files/usr/lib/go/src/net/http/server.go:2936 +0x2c0
net/http.(*conn).serve(0x4000370120, {0x5936298fa8, 0x400007fb60})
        /data/data/com.termux/files/usr/lib/go/src/net/http/server.go:1995 +0x518
created by net/http.(*Server).Serve
        /data/data/com.termux/files/usr/lib/go/src/net/http/server.go:3089 +0x4e8

**Comment by Mr-Octopus-2020** [comment]
Fedora Linux 40上出现相同问题。日志如下：

` ./maimaidx-prober-proxy-linux-amd64-1.3.3 
2025/06/28 23:43:19 INFO: 您使用的是最新版本。
2025/06/28 23:43:20 INFO: 登录成功
2025/06/28 23:43:20 INFO: 使用此软件则表示您同意共享您在微信公众号舞萌 DX、中二节奏中的数据。
2025/06/28 23:43:20 INFO: 您可以在微信客户端访问微信公众号舞萌 DX、中二节奏的个人信息主页进行分数导入，如需退出请直接关闭程序或按下 Ctrl + C
2025/06/28 23:43:20 INFO: 代理已开启到 127.0.0.1:8033
2025/06/28 23:45:22 http: panic serving 127.0.0.1:49970: runtime error: index out of range [0] with length 0
goroutine 145 [running]:
net/http.(*conn).serve.func1()
        net/http/server.go:1854 +0xbf
panic({0x7319a0, 0xc0005cc060})
        runtime/panic.go:890 +0x263
github.com/elazarl/goproxy.signHost({{0x0, 0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/elazarl/goproxy@v0.0.0-20221015165544-a0805db90819/signer.go:44 +0xad8
github.com/elazarl/goproxy.TLSConfigFromCA.func1.1(...)
        github.com/elazarl/goproxy@v0.0.0-20221015165544-a0805db90819/https.go:465
github.com/elazarl/goproxy.TLSConfigFromCA.func1({0xc000126047, 0x15}, 0xc000594120)
        github.com/elazarl/goproxy@v0.0.0-20221015165544-a0805db90819/https.go:470 +0x208
github.com/elazarl/goproxy.(*ProxyHttpServer).handleHttps(0xc00017a160, {0x7d70c0?, 0xc0000d8000}, 0xc0000f2200)
        github.com/elazarl/goproxy@v0.0.0-20221015165544-a0805db90819/https.go:205 +0x504
github.com/elazarl/goproxy.(*ProxyHttpServer).ServeHTTP(0x0?, {0x7d70c0, 0xc0000d8000}, 0xc0000f2200)
        github.com/elazarl/goproxy@v0.0.0-20221015165544-a0805db90819/proxy.go:129 +0xd7
net/http.serverHandler.ServeHTTP({0xc000096d50?}, {0x7d70c0, 0xc0000d8000}, 0xc0000f2200)
        net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc00051c000, {0x7d72e8, 0xc000218300})
        net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
        net/http/server.go:3089 +0x5ed`
