### ISSUE TITLE
macOS下查分程序Runtime Error

### ISSUE THREAD

**Issue by LostConnet** [Diving-Fish/maimaidx-prober#52]
### 系统信息
**OS: macOS 12.6
Device: MacBookPro2019 late 16-Inch
CPU: intel core i7-9750H**
### 软件版本
[Release:1.2.0-fix1](https://github.com/Diving-Fish/maimaidx-prober/releases/tag/1.2.0-fix1)
### 错误代码
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x12ba705]

goroutine 22 [running]:
main.commit({0x13c90e0?, 0xc000308040?})
	C:/Users/DivingFish/Github/maimaidx-prober/proxy/cmd/maimaidx-prober-proxy/main.go:71 +0x65
main.fetchData(0xc000160300, {0xc000224008, 0x1, 0x1})
	C:/Users/DivingFish/Github/maimaidx-prober/proxy/cmd/maimaidx-prober-proxy/main.go:102 +0x5e5
created by main.main.func2
	C:/Users/DivingFish/Github/maimaidx-prober/proxy/cmd/maimaidx-prober-proxy/main.go:213 +0x29a

```
###发生时机
成功开启代理后，在微信中打开舞萌DX公众号，显示代理连接成功，然后Terminal中程序发生报错

**Comment by LostConnet** [comment]
这是奇怪的，mac设备不应当有类似「C:/」这样的路径描述，并且路径中出现了开发者的用户名「DivingFish」，我去检查源代码，并未发现有包含开发者用户名写死的路径

**Comment by Diving-Fish** [comment]
这个是因为编译的时候把符号文件也编译进去了，所以会根据报错的内存位置去找对应的代码行
空指针的原因一般情况是json配置文件有问题，请检查您的配置文件的编码和格式是否有误

**Comment by LostConnet** [comment]
好的，我回去检查

**Comment by LostConnet** [comment]
检查了json，是没有问题的，编码也是utf-8，我去尝试一下go run源码有无问题吧
